# Generated by Django 5.0.6 on 2026-10-02 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('actual_load', models.FloatField(help_text='Station load in kW at time of session')),
                ('charging_power_kW', models.FloatField()),
                ('energy_kWh', models.FloatField(help_text='Energy delivered, NOT load')),
                ('duration', models.FloatField(help_text='Duration in hours')),
                ('traffic_density', models.IntegerField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High')], default=0)),
                ('weather_condition', models.CharField(choices=[('Clear', 'Clear'), ('Cloudy', 'Cloudy'), ('Rainy', 'Rainy')], default='Clear', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookings.booking')),
                ('charger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.charger')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.station')),
            ],
        ),
    ]
