# Generated by Django 6.0.3 on 2026-10-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='price_per_kWh',
            field=models.DecimalField(decimal_places=2, default=18.0, help_text='Tariff in rupees per kWh, used to bill completed sessions', max_digits=6),
        ),
    ]
